name: schmucklicloud_auth
description: The official schmuckliCloud Authentication SDK for Dart. Use this SDK if you want to install a fully functional authentication system in your apps.
version: 1.0.0
author: schmuckli.dev <julian@schmuckli.net>
homepage: https://schmuckli.cloud
repository: https://github.com/julianschmuckli/schmucklicloud_sdk_dart/tree/master/auth
issue_tracker: https://github.com/julianschmuckli/schmucklicloud_sdk_dart/issues
documentation: https://docs.schmuckli.cloud/sdk_for_dart/auth
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: ^0.12.0