name: schmucklicloud_storage
description: The official schmuckliCloud Storage SDK for Dart. Use this SDK if you want store and manage data from the Cloud.
version: 0.1.4
author: schmuckli.dev <julian@schmuckli.net>
homepage: https://schmuckli.cloud
repository: https://github.com/julianschmuckli/schmucklicloud_sdk_dart/tree/master/storage
issue_tracker: https://github.com/julianschmuckli/schmucklicloud_sdk_dart/issues
documentation: https://docs.schmuckli.cloud/sdk_for_dart/storage
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: ^0.12.0